---
- hosts: all
  become: yes
  remote_user: ahre #replace with yours defined in terraform variable user

  tasks:
  - name: Ensure ntp (for time synchronization) is installed.
    apt:
      name: ntp
      state: present


  - name: Ensure ntp is running.
    service:
      name: ntp
      state: started
      enabled: yes

- hosts: web
  become: yes
  remote_user: ahre #replace with yours defined in terraform variable user

  tasks:
  - name: Ensure nginx is installed.
    apt:
      name: nginx
      state: present

  - name: Ensure nginx is running.
    service:
      name: nginx
      state: started
      enabled: yes
